### ISSUE TITLE
[OTHER] Adopt repo-review for tephi

### ISSUE THREAD

**Issue by ESadek-MO** [SciTools/tephi#155]
## ❓ Other

Adopt and align tephi with [repo review](https://learn.scientific-python.org/development/guides/repo-review/?repo=scitools%2Ftephi&branch=main), as in [cf-units](https://github.com/SciTools/cf-units/pull/456/files).

```[tasklist]
### Tasks
- [x] Adopt repo review, with all checks ignored for the time being (#164)
- [x] Decide which standards should be maintained for tephi ([below](https://github.com/SciTools/tephi/issues/155#issuecomment-2454560289))
- [x] Implement changes so that tephi is in-line with these standards
```

```[tasklist]
### Repo Review Errors
- [x] PP301 - pytest isn't present in pyproject.toml. (#177)
- [x] GH212 - Need to add github groups (#179)
- [x] PC170 - Add a pygrep hook (#179)
- [x] PC901 - Add custom ci message (via dependabot) (#179)
- [ ] PP309 - need to add filterwarnings
```

**Comment by ESadek-MO** [comment]
I think we should aim to include:

- [ ]   PY005:  - Has tests folder 
- [ ]   PP003:  - Does not list wheel as a build-dep 
- [ ]   PP301:  - Has pytest in project
- [ ]   PP309:  - Filter warnings specified
- [ ]   PC110:  - Uses black or ruff-format 
- [ ]   PC140:  - Uses a type checker 
- [ ]   PC160:  - Uses a spell checker 
- [ ]   PC170:  - Uses PyGrep hooks (only needed if rST present) 
- [ ]   PC190:  - Uses Ruff 
- [ ]   PC901:  - Custom pre-commit CI message 
- [ ]   RF001:  - Has Ruff config 

With these being nice to haves:

- [ ]   PP304:  - Sets the log level in pytest
- [ ]   PP305:  - Specifies xfail_strict
- [ ]   PP306:  - Specifies strict config
- [ ]   PP307:  - Specifies strict markers
- [ ]   GH212:  - Require GHA update grouping
- [ ]   PC180:  - Uses a markdown formatter 
- [ ]   MY100:  - Uses MyPy (pyproject config) 

@bjlittle that sound about right?

**Comment by trexfeathers** [comment]
>PC180: - Uses a markdown formatter

FYI we have been forced to ignore this one pretty much everywhere. I believe this is due to temporary limitations of the hardware most SciTools developers work on.
